FROM mcr.microsoft.com/devcontainers/base:alpine-3.20
# COPY index.html /usr/share/nginx/html/index.html
# COPY script.js /usr/share/nginx/html/script.js
# COPY style.css /usr/share/nginx/html/style.css